CREATE TABLE project
(
ID INT(9) PRIMARY KEY AUTO_INCREMENT,
PROJECT VARCHAR(100) NOT NULL,
START_DATE DATE,
END_DATE DATE,
PRIORITY INT(2) DEFAULT 0
);

ALTER TABLE users ADD COLUMN PROJECT_ID INT(9);
ALTER TABLE users ADD CONSTRAINT fk_project_id FOREIGN KEY (PROJECT_ID) REFERENCES project(ID);
