ALTER TABLE users ADD COLUMN TASK_ID INT(9);
ALTER TABLE users ADD CONSTRAINT fk_task_id FOREIGN KEY (TASK_ID) REFERENCES task(ID);

ALTER TABLE task ADD COLUMN PROJECT_ID INT(9);
ALTER TABLE task ADD COLUMN STATUS VARCHAR(50);
ALTER TABLE task ADD CONSTRAINT fk_task_project_id FOREIGN KEY (PROJECT_ID) REFERENCES project(ID);

