version: '2.2'
services:
  app:
   restart: always
    build:
      context: ./
      dockerfile: Dockerfile-Build
    image: appWeb
    ports:
      - 8080
    scale: 2
    depends_on:
          - mysql

  mysql:
      container_name: mysql-standalone
      image: mysql/mysql-server:latest
      environment:
        MYSQL_DATABASE: cogdb
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_ROOT_HOST: '%'
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
      ports:
        - "3306:3306"
      restart: always